server:
  port: 8080

#logging:
#  level:
#    root: debug
spring:
  datasource:
#    url: jdbc:mysql://52.77.251.94:3306/test
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=bagana.novo.dk)(PORT=16030))(ADDRESS=(PROTOCOL=TCP)(HOST=groppo.novo.dk)(PORT=16030)))(CONNECT_DATA=(SERVICE_NAME=pems8v_rw.novo.dk)))
    username: pemsreadonly
    password: readonly_PEMS_8V
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 3000000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
